#!/usr/bin/env -S ansible-playbook --ask-become-pass
- name: Debian Workstation
  hosts: 127.0.0.1
  connection: local
  become: true
  pre_tasks:
    - name: Install apt https tranport
      ansible.builtin.apt:
        name: apt-transport-https
        update_cache: true
        state: latest
  roles:
    - role: firefox
    - role: chrome
    - role: vscode
    - role: docker
    - role: golang
    - role: nodejs
    - role: flatpak
      vars:
        flatpak_apps:
          - com.spotify.Client
