- name: Add Microsoft apt repository key.
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.com.asc
    mode: "0644"
    force: true

- name: Add Microsoft Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.com.asc] http://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Update apt and install VSCode
  ansible.builtin.apt:
    name: code
    state: latest
    update_cache: true
