- name: Add Nodesource apt repository key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: "0644"
    force: true

- name: Add NodeSource deb repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_22.x nodistro main'
    filename: nodesource.list
    state: present

- name: Add NodeSource repository preferences
  ansible.builtin.copy:
    src: nodesource.pref
    dest: /etc/apt/preferences.d/nodesource.pref

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: latest
    update_cache: yes
