- name: Install flatpak
  ansible.builtin.apt:
    name: flatpak
    state: latest
    update_cache: true

- name: Install GNOME Flatpak Plugin
  ansible.builtin.apt:
    name: gnome-software-plugin-flatpak
    state: latest
  when: "ansible_env['XDG_CURRENT_DESKTOP']|default('') == 'GNOME'"

- name: Install KDE Flatpak Plugin
  ansible.builtin.apt:
    name: plasma-discover-backend-flatpak
    state: latest
  when: "ansible_env['XDG_CURRENT_DESKTOP']|default('') == 'KDE'"

- name: Setup flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install Flatpaks
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: latest
    method: system
  with_items: "{{ flatpak_apps }}"
