---
driver:
  name: podman
platforms:
  - name: molecule-debian12
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
