- name: Add Google apt repository key.
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google.asc
    mode: "0644"
    force: true

- name: Add Google Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/google.asc] https://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome-ansible
    state: present

- name: Update apt and install google-chrome-stable
  ansible.builtin.apt:
    name: google-chrome-stable
    state: latest
    update_cache: true

- name: Verify in google-chrome-stable's apt sources exist
  stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: google_chrome_sources

- name: Disable google-chrome-stable's apt sources
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/google-chrome.list
    regex: "^(deb.+)$"
    line: "# \\1"
    backrefs: true
  when: google_chrome_sources.stat.exists
